// Generated from the workbook Definitions sheet (C2:C61). Source is sheet then cell, so every entry can be traced.
// The labeled inputs and the calculation rules in this engine govern results; these are reading aids.
export type GlossaryEntry = { section: string; name: string; definition: string; source: string };

export const GLOSSARY: GlossaryEntry[] = [
  {"section": "Header", "name": "Property Address", "definition": "The address of the property you want to analyze", "source": "Definitions C2"},
  {"section": "Header", "name": "Total Square Footage", "definition": "The total square footage of the entire interior of the property", "source": "Definitions C3"},
  {"section": "Header", "name": "Evaluator Name", "definition": "Name of the evaluator.", "source": "Definitions C4"},
  {"section": "Header", "name": "Property Description", "definition": "Key details and attributes about the property including differentiators, # of garage spaces, levels, layout, property type, etc.", "source": "Definitions C5"},
  {"section": "Property Values / Pricing", "name": "Property Values / Pricing", "definition": "Section to enter property value and purchase figures for helping calculate profit", "source": "Definitions C6"},
  {"section": "Property Values / Pricing", "name": "After Repair Value", "definition": "Value of the property after all repairs have been made regardless of purchase price. Also known as \"Fair Market Value\"", "source": "Definitions C7"},
  {"section": "Property Values / Pricing", "name": "Current Value \"As Is\"", "definition": "Value of the property in current \"as is\" condition. Not factoring repairs needed.", "source": "Definitions C8"},
  {"section": "Property Values / Pricing", "name": "Estimated Repair Costs", "definition": "The dollar amount of estimated repairs based on your analysis", "source": "Definitions C9"},
  {"section": "Property Values / Pricing", "name": "Purchase Price", "definition": "The dollar amount you plan to purchase the property for", "source": "Definitions C10"},
  {"section": "Property Values / Pricing", "name": "Estimated Hold Time months", "definition": "Estimated number of months you plan to own the property from purchase date to close of escrow sale date", "source": "Definitions C11"},
  {"section": "Financing Costs", "name": "Financing Costs", "definition": "Section to enter the different amounts you will borrow to purchase the property.", "source": "Definitions C12"},
  {"section": "Financing Costs", "name": "First Mortgage / Lien Amount", "definition": "The 1st position loan amount borrowed to purchase the property and / or fund the rehab", "source": "Definitions C13"},
  {"section": "Financing Costs", "name": "First Mortgage Points", "definition": "The 1st position points charged as a % of Mortgage Lien Amount. 1 Point = 1% in calculation.", "source": "Definitions C14"},
  {"section": "Financing Costs", "name": "First Mortgage Interest Rate", "definition": "The 1st position Interest rate for amount borrowed to purchase the property and / or fund the rehab", "source": "Definitions C15"},
  {"section": "Financing Costs", "name": "First Mortgage Monthly Interest Only Payment", "definition": "The 1st position Interest only monthly payment amount if required by lender.", "source": "Definitions C16"},
  {"section": "Financing Costs", "name": "Second Mortgage / Lien Amount", "definition": "The 2nd position loan amount borrowed to purchase the property and / or fund the rehab", "source": "Definitions C17"},
  {"section": "Financing Costs", "name": "Second Mortgage Points", "definition": "The 2nd position points charged as a % of Mortgage Lien Amount. 1 Point = 1% in calculation.", "source": "Definitions C18"},
  {"section": "Financing Costs", "name": "Second Mortgage Interest Rate", "definition": "The 2nd position Interest rate for amount borrowed to purchase the property and / or fund the rehab", "source": "Definitions C19"},
  {"section": "Financing Costs", "name": "Second Mortgage Monthly Interest Only Payment", "definition": "The 2nd position Interest only monthly payment amount if required by lender.", "source": "Definitions C20"},
  {"section": "Financing Costs", "name": "Misc. Mortgage / Lien Amount", "definition": "The misc. position loan amount borrowed to purchase the property and/or fund the rehab.", "source": "Definitions C21"},
  {"section": "Financing Costs", "name": "Misc. Mortgage Points", "definition": "The Misc. position points charged as a % of Mortgage Lien Amount. 1 Point = 1% in calculation.", "source": "Definitions C22"},
  {"section": "Financing Costs", "name": "Misc. Mortgage Interest Rate", "definition": "The misc. position Interest rate for amount borrowed to purchase the property and/or fund the rehab.", "source": "Definitions C23"},
  {"section": "Financing Costs", "name": "Misc. Mortgage Interest Only Payment", "definition": "The misc. position Interest only monthly payment amount if required by lender.", "source": "Definitions C24"},
  {"section": "Financing Costs", "name": "Financing Origination Costs", "definition": "Financing Origination Costs - for a mortgage approximately 1% of purchase price plus $1,000", "source": "Definitions C25"},
  {"section": "Financing Costs", "name": "Miscellaneous Financing Costs", "definition": "Any custom costs related to Financing.", "source": "Definitions C26"},
  {"section": "Holding Costs", "name": "Holding Costs", "definition": "Section to enter costs related to time property is held. Costs are typically tracked and calculated on a monthly basis", "source": "Definitions C27"},
  {"section": "Holding Costs", "name": "Property Taxes", "definition": "Use default or enter the actual Annualized property taxes as reported on the county tax assessors website or enter an estimate, or use the default values stored", "source": "Definitions C28"},
  {"section": "Holding Costs", "name": "HOA / Condo Fees", "definition": "Use default or enter the Home Owner Association fees typically charged monthly.", "source": "Definitions C29"},
  {"section": "Holding Costs", "name": "Insurance Costs Vacant", "definition": "Use default or enter the Vacant property insurance premium typically billed monthly. Typically more expensive than Occupied insurance.", "source": "Definitions C30"},
  {"section": "Holding Costs", "name": "Insurance Costs Occupied", "definition": "Use default or enter the Occupied property insurance premium typically billed monthly. Typically less expensive than Vacant insurance.", "source": "Definitions C31"},
  {"section": "Holding Costs", "name": "Utility Costs", "definition": "Combined value for gas, electricity, water utilities.", "source": "Definitions C32"},
  {"section": "Holding Costs", "name": "Miscellaneous Holding Costs", "definition": "Enter any custom costs related to holding the property.", "source": "Definitions C33"},
  {"section": "Buying Transaction Costs", "name": "Buying Transaction Costs", "definition": "Section for entering and tracking buying transaction costs", "source": "Definitions C34"},
  {"section": "Buying Transaction Costs", "name": "Escrow / Attorney Fees", "definition": "Fees charged by attorney or escrow company at closing. Typically a % of sales price. Make sure you use appropriate formula based on if you are in an Attorney or Escrow state.", "source": "Definitions C35"},
  {"section": "Buying Transaction Costs", "name": "Title Insurance / Title Search Costs", "definition": "Policy to insure clear and marketable title. Changes based on area, type of policy, underwriter", "source": "Definitions C36"},
  {"section": "Buying Transaction Costs", "name": "Miscellaneous Buying Costs", "definition": "Enter any custom costs related to Buying transactions.", "source": "Definitions C37"},
  {"section": "Selling Transaction Costs", "name": "Selling Transaction Costs", "definition": "Section for entering and tracking selling transaction costs", "source": "Definitions C38"},
  {"section": "Selling Transaction Costs", "name": "Escrow / Attorney Fees", "definition": "Fees charged by attorney or escrow company at closing. Typically a % of sales price. Make sure you use appropriate formula based on if you are in an Attorney or Escrow state.", "source": "Definitions C39"},
  {"section": "Selling Transaction Costs", "name": "Selling Recording Fees", "definition": "Fees taken from the HUD-1 County recorders fees charged by escrow company", "source": "Definitions C40"},
  {"section": "Selling Transaction Costs", "name": "Realtor Fees", "definition": "Commissions paid to realtors involved as part of the transaction", "source": "Definitions C41"},
  {"section": "Selling Transaction Costs", "name": "Conveyance / Transfer Fees", "definition": "For the transfer of land charged by County from seller to buyer. Typically a % of the land value based on county assessor valuation", "source": "Definitions C42"},
  {"section": "Selling Transaction Costs", "name": "Home Warranty", "definition": "Offers protection for mechanical systems and attached appliances against unexpected repairs not covered by homeowner's insurance; overage extends over a specific time period and does not cover the home's structure", "source": "Definitions C43"},
  {"section": "Selling Transaction Costs", "name": "Staging Costs", "definition": "Cost for getting property ready to sell by bringing in home furnishings.", "source": "Definitions C44"},
  {"section": "Selling Transaction Costs", "name": "Marketing Costs", "definition": "Costs related to offline and online advertising, printing, and promotion to help sell the property.", "source": "Definitions C45"},
  {"section": "Selling Transaction Costs", "name": "Miscellaneous Selling Costs", "definition": "Enter any custom costs related to Selling transactions.", "source": "Definitions C46"},
  {"section": "Deal Summary & Potential Profit", "name": "Deal Summary & Potential Profit", "definition": "Section breaks down the revenue and expenses of the entire project", "source": "Definitions C47"},
  {"section": "Deal Summary & Potential Profit", "name": "After Repair Value", "definition": "Value of the property after all repairs have been made regardless of purchase price. Also known as \"Fair Market Value\"", "source": "Definitions C48"},
  {"section": "Deal Summary & Potential Profit", "name": "Purchase Price", "definition": "The dollar amount you plan to purchase the property for.", "source": "Definitions C49"},
  {"section": "Deal Summary & Potential Profit", "name": "Estimated Repair Costs", "definition": "The dollar amount of estimated repairs based on your analysis and assessment.", "source": "Definitions C50"},
  {"section": "Deal Summary & Potential Profit", "name": "Total Financing Costs", "definition": "Total Borrowing Costs of first, second, and misc. rehab financing fees, points, and interest charged over duration of the project", "source": "Definitions C51"},
  {"section": "Deal Summary & Potential Profit", "name": "Total Holding Costs", "definition": "Total Costs for all monthly carrying expenses based on the duration of how long property is held between purchase and sales date.", "source": "Definitions C52"},
  {"section": "Deal Summary & Potential Profit", "name": "Total Buying Transaction Costs", "definition": "Total transactional costs related to the buying phase of the transaction", "source": "Definitions C53"},
  {"section": "Deal Summary & Potential Profit", "name": "Total Selling Transaction Costs", "definition": "Total transactional costs related to the selling phase of the transaction.", "source": "Definitions C54"},
  {"section": "Deal Summary & Potential Profit", "name": "Estimated NET PROFIT", "definition": "Difference between the revenue and expenses of the entire project before income taxes.", "source": "Definitions C55"},
  {"section": "Potential Return & Profit Analysis", "name": "Potential Return & Profit Analysis", "definition": "Section Summary of key profit and deal value measurements", "source": "Definitions C56"},
  {"section": "Potential Return & Profit Analysis", "name": "My Committed Capital", "definition": "Amount of your own money out of pocket that you put in the deal as the purchaser", "source": "Definitions C57"},
  {"section": "Potential Return & Profit Analysis", "name": "Repair Estimate Cost Per Sq. Ft", "definition": "Total Purchase+Rehab Estimate costs divided by total square feet of the property used as a measurement market indicator", "source": "Definitions C58"},
  {"section": "Potential Return & Profit Analysis", "name": "Down Payment Required at Closing", "definition": "Amount required by you at closing", "source": "Definitions C59"},
  {"section": "Potential Return & Profit Analysis", "name": "Purchase + Rehab Return on Investment ROI", "definition": "% of interest earned based on purchase + rehab costs regardless of how long the property was held.", "source": "Definitions C60"},
  {"section": "Potential Return & Profit Analysis", "name": "Total Costs Return on Investment ROI", "definition": "% of interest earned based on purchase +ALL costs regardless of how long the property was held", "source": "Definitions C61"},
];

export const GLOSSARY_SECTIONS: string[] = Array.from(new Set(GLOSSARY.map((g) => g.section)));
