/**
 * Copies the SQL migrations into src/migrations.generated.ts so the migrator
 * needs no filesystem at runtime. Serverless bundles do not carry the
 * migrations folder and bake build time paths into import.meta.url.
 * Run after every `drizzle-kit generate`: pnpm --filter @dealcalc/db generate
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const migrationsDir = resolve(here, "../migrations");
const outFile = resolve(here, "../src/migrations.generated.ts");

const files = readdirSync(migrationsDir).filter((f) => /^\d{4}_.*\.sql$/.test(f)).sort();
const entries = files.map((f) => {
  const text = readFileSync(resolve(migrationsDir, f), "utf-8").replace(/\r\n/g, "\n");
  return `  ${JSON.stringify(f)}: ${JSON.stringify(text)},`;
});

const source = [
  "// Generated by scripts/embed-migrations.ts. Do not edit. Regenerate with: pnpm --filter @dealcalc/db generate",
  "export const EMBEDDED_MIGRATIONS: Record<string, string> = {",
  ...entries,
  "};",
  "",
].join("\n");

writeFileSync(outFile, source);
console.log(`Embedded ${files.length} migration file(s) into ${outFile}`);
