/** The 67 rows of the Rehab Estimator sheet, unit costs as typed in column H (workbook defaults). */
export type ChecklistRow = { row: number; itemNumber: number | null; question: string | null; option: string | null; unitCost: number | null; unit: string; perSqft?: boolean };

export const REHAB_CHECKLIST: ChecklistRow[] = [
  { row: 3, itemNumber: 1, question: "Need a Roof?", option: "Single", unitCost: 6000, unit: "each" },
  { row: 4, itemNumber: null, question: null, option: "Full Roof Multi Unit", unitCost: 9000, unit: "each" },
  { row: 5, itemNumber: null, question: null, option: "1 Layer of Shingles Added, Low", unitCost: 2500, unit: "each" },
  { row: 6, itemNumber: null, question: null, option: "1 Layer of Shingles Added, High", unitCost: 3000, unit: "each" },
  { row: 7, itemNumber: 2, question: "Exterior Paint/Siding?", option: "Paint Single Fam Home", unitCost: 3000, unit: "each" },
  { row: 8, itemNumber: null, question: null, option: "Paint Multi Fam, Low, 1500 sq ft", unitCost: 6000, unit: "each" },
  { row: 9, itemNumber: null, question: null, option: "Paint Multi Fam, Low, 3000 sq ft", unitCost: 7000, unit: "each" },
  { row: 10, itemNumber: null, question: null, option: "Siding Single Fam, Low, 1500 sq ft", unitCost: 7000, unit: "each" },
  { row: 11, itemNumber: null, question: null, option: "Siding Multi Fam, Low, 3000 sq ft", unitCost: 11000, unit: "each" },
  { row: 12, itemNumber: 3, question: "Need Windows?", option: "Cost/Window", unitCost: 250, unit: "window" },
  { row: 13, itemNumber: 4, question: "Garage Repair?", option: "Garage Door", unitCost: 550, unit: "each" },
  { row: 14, itemNumber: null, question: null, option: "Reframe Structure", unitCost: 1500, unit: "each" },
  { row: 15, itemNumber: null, question: null, option: "1 Car Garage Paint", unitCost: 500, unit: "each" },
  { row: 16, itemNumber: null, question: null, option: "2 Car Garage Paint", unitCost: 1000, unit: "each" },
  { row: 17, itemNumber: null, question: null, option: "Roof", unitCost: 2000, unit: "each" },
  { row: 18, itemNumber: 5, question: "Yard Cleaned/Landscapes", option: "Clean Yard, Easy", unitCost: 5000, unit: "each" },
  { row: 19, itemNumber: null, question: null, option: "Clean Yard, Hard", unitCost: 750, unit: "each" },
  { row: 20, itemNumber: null, question: null, option: "Landscape, Easy", unitCost: 500, unit: "each" },
  { row: 21, itemNumber: null, question: null, option: "Landscape, Hard", unitCost: 1000, unit: "each" },
  { row: 22, itemNumber: 6, question: "Heating or Furnaces Need Replacing?", option: "Replace Furnace", unitCost: 1500, unit: "each" },
  { row: 23, itemNumber: null, question: null, option: "Replace Hot Water Heater", unitCost: 600, unit: "each" },
  { row: 24, itemNumber: null, question: null, option: "Install Zone Baseboard Heater Gut Job", unitCost: 4500, unit: "each" },
  { row: 25, itemNumber: 7, question: "Plumbing need Repair?", option: "New Plumbing/Floor", unitCost: 2500, unit: "each" },
  { row: 26, itemNumber: 8, question: "Electrical Need Repair", option: "New Panel", unitCost: 1500, unit: "each" },
  { row: 27, itemNumber: null, question: null, option: "Floor Fixtures That Need New Fixtures", unitCost: 200, unit: "fixture" },
  { row: 28, itemNumber: null, question: null, option: "Rewire House w/ New Service", unitCost: 4000, unit: "floor" },
  { row: 29, itemNumber: 9, question: "Foundation Need Repair?", option: "Reframe Support Beam", unitCost: 300, unit: "each" },
  { row: 30, itemNumber: 10, question: "Basement Need Repair?", option: "Seal Basement", unitCost: 250, unit: "each" },
  { row: 31, itemNumber: null, question: null, option: "Pour Concrete Floor", unitCost: 800, unit: "5 yard increment" },
  { row: 32, itemNumber: null, question: null, option: "Replace Stairwell", unitCost: 1000, unit: "each" },
  { row: 33, itemNumber: null, question: null, option: "Jack 1 Support Beam", unitCost: 200, unit: "each" },
  { row: 34, itemNumber: 11, question: "Need Interior Paint", option: "Per square foot", unitCost: 2, unit: "sqft", perSqft: true },
  { row: 35, itemNumber: null, question: null, option: "Single Family 1500 sq ft", unitCost: 2500, unit: "each" },
  { row: 36, itemNumber: null, question: null, option: "Three Family Home 3000 sq ft", unitCost: 4500, unit: "each" },
  { row: 37, itemNumber: 12, question: "House Need Carpet?", option: "Single Family Carpet", unitCost: 1500, unit: "each" },
  { row: 38, itemNumber: 13, question: "House Need Tile/Vinyl", option: "Three Family Home", unitCost: 2000, unit: "each" },
  { row: 39, itemNumber: 14, question: "Floor need to be sanded?", option: "1 Unit Carpet 500 sq ft ($500 rule: sq ft / 9 x $10)", unitCost: null, unit: "sqft" },
  { row: 40, itemNumber: null, question: null, option: "1 Unit Carpet 500 sq ft ($500 rule: sq ft / 9 x $10)", unitCost: null, unit: "sqft" },
  { row: 41, itemNumber: null, question: null, option: "Kitchen Vinyl tiles 10x10 ($700)", unitCost: null, unit: "kitchen" },
  { row: 42, itemNumber: null, question: null, option: "Hardwood Install $7.00 sq ft, Sand and Refinish $2.75 sq ft", unitCost: null, unit: "sqft" },
  { row: 43, itemNumber: 15, question: "Unit 1 Kitchen Need Repair", option: "Single Fam Rental", unitCost: 2000, unit: "each" },
  { row: 44, itemNumber: 16, question: "Unit 2 Kitchen Need Repair?", option: "Three Fam Rental", unitCost: 6000, unit: "each" },
  { row: 45, itemNumber: 17, question: "Unit 3 Kitchen Need Repair?", option: "Single Fam Owner", unitCost: 3500, unit: "each" },
  { row: 46, itemNumber: null, question: null, option: "Three Fam Owner", unitCost: 7500, unit: "each" },
  { row: 47, itemNumber: null, question: null, option: "Single Family Nice", unitCost: 4000, unit: "each" },
  { row: 48, itemNumber: 18, question: "Kitchen Need Appliances?", option: "Stove", unitCost: 350, unit: "each" },
  { row: 49, itemNumber: null, question: null, option: "Refrigerator", unitCost: 500, unit: "each" },
  { row: 50, itemNumber: null, question: null, option: "Overhead Microwave", unitCost: 200, unit: "each" },
  { row: 51, itemNumber: null, question: null, option: "Dishwasher", unitCost: 250, unit: "each" },
  { row: 52, itemNumber: 19, question: "Unit 1 Bath need Repair?", option: "Redo Full Bath", unitCost: 1500, unit: "each" },
  { row: 53, itemNumber: 20, question: "Unit 2 Bath need Repair?", option: "Redo Half Bath", unitCost: 1000, unit: "each" },
  { row: 54, itemNumber: 21, question: "Unit 3 Bath need Repair?", option: "Fixtures only Full Bath", unitCost: 500, unit: "each" },
  { row: 55, itemNumber: null, question: null, option: "Fixtures Only Half Bath", unitCost: 350, unit: "each" },
  { row: 56, itemNumber: 22, question: "Sheetrock damaged or Need Replacing?", option: "Total Gut Job per square foot", unitCost: 3, unit: "sqft", perSqft: true },
  { row: 57, itemNumber: null, question: null, option: "Single Fam Patch, Low", unitCost: 500, unit: "each" },
  { row: 58, itemNumber: null, question: null, option: "Single Fam Patch, High", unitCost: 1000, unit: "each" },
  { row: 59, itemNumber: null, question: null, option: "Single Fam Gut Rock/Tape, Low", unitCost: 9000, unit: "each" },
  { row: 60, itemNumber: null, question: null, option: "Single Fam Gut Rock/Tape, High", unitCost: 10000, unit: "each" },
  { row: 61, itemNumber: null, question: null, option: "Patch Area 10x10", unitCost: 300, unit: "each" },
  { row: 62, itemNumber: 23, question: "Dumpsters", option: "Dumpster, Low", unitCost: 500, unit: "each" },
  { row: 63, itemNumber: null, question: null, option: "Dumpster, High", unitCost: 600, unit: "each" },
  { row: 64, itemNumber: null, question: null, option: "Single Family Patch 3 Dumps", unitCost: 1000, unit: "each" },
  { row: 65, itemNumber: null, question: null, option: "Family Gut", unitCost: 3500, unit: "each" },
  { row: 66, itemNumber: 24, question: "Decks", option: "Deck 10x10", unitCost: 2000, unit: "each" },
  { row: 67, itemNumber: null, question: null, option: "Deck 15x15", unitCost: 3500, unit: "each" },
  { row: 68, itemNumber: null, question: null, option: "3 Family w/ Fire Escape", unitCost: 5000, unit: "each" },
  { row: 69, itemNumber: 25, question: "Miscellaneous", option: "Per square foot", unitCost: 0.5, unit: "sqft", perSqft: true },
];
